version: '3.9'

services:
  postgres:
    build:
      context: ./database  
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres_root", "-d", "todoo"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  express-app:
    build:
      context: ./server
    env_file:
      - .env
    ports:
      - "${EXPRESS_APP_PORT}:${EXPRESS_APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./server:/usr/src/app
    command: sh -c "printenv && node dist/index.js"

  react-app:
    build:
      context: ./client
    env_file:
      - .env
    ports:
      - "${REACT_APP}:${REACT_APP}"
    depends_on:
      - express-app
    volumes:
      - ./client:/usr/src/app

  nginx:
    build:
      context: ./nginx
    env_file:
      - .env
    ports:
      - "80:80" 
    depends_on:
      - postgres
      - express-app
      - react-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf